# .readthedocs.yaml

version: 2

# Specify the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # Or another suitable version

  # Add custom build steps
  jobs:
    post_build:
      # These commands run AFTER the standard Sphinx build.

      # Copy EACH required static file EXPLICITLY.
      # This is the most reliable way to ensure all assets (HTML, CSS, JS, images)
      # end up in the final build, overwriting Sphinx files.
      # The -f (force) flag ensures overwriting.
      - echo "--- Copying static files ---"
      - cp -rf _static_html/index.html $READTHEDOCS_OUTPUT/html/index.html
      - cp -rf _static_html/style.css $READTHEDOCS_OUTPUT/html/style.css
      - cp -rf _static_html/Letsencrypt-logo-horizontal.svg $READTHEDOCS_OUTPUT/html/Letsencrypt-logo-horizontal.svg
      # Add cp commands for EACH other asset here if needed in the future:
      # - cp -rf _static_html/page2.html $READTHEDOCS_OUTPUT/html/page2.html
      # - cp -rf _static_html/script.js $READTHEDOCS_OUTPUT/html/script.js
      # - cp -rf _static_html/images/logo.png $READTHEDOCS_OUTPUT/html/images/logo.png

# Point Sphinx to our minimal conf.py
sphinx:
  configuration: docs/conf.py

# Specify how to install Python dependencies
python:
  install:
    - requirements: requirements.txt

# (Optional) Specify which formats to build
formats:
 - htmlzip
 # - pdf